name: Java CI with Lint, Tests, Coverage, and Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Run Spotless (Lint)
      run: mvn spotless:check

    - name: Run Unit Tests with Coverage
      run: mvn test jacoco:report

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Run PMD
      run: mvn pmd:check

    - name: Run SpotBugs
      run: mvn com.github.spotbugs:spotbugs-maven-plugin:check
